version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - ireturn
    - lll
    - maintidx
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - promlinter
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    gocyclo:
      min-complexity: 20
    testifylint:
      enable-all: true
      disable:
        - suite-thelper
        - float-compare
        - require-error
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: '^(G104|G204):'
      - path: (.+)\.go$
        text: Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: exported method (.*\.MarshalJSON|.*\.UnmarshalJSON) should have comment or be unexported
      - path: (.+)\.go$
        text: composite literal uses unkeyed fields
      - path: (.+)\.go$
        text: bad syntax for struct tag key
      - path: (.+)\.go$
        text: bad syntax for struct tag pair
      - path: (.+)\.go$
        text: result .* \(error\) is always nil
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
