services:
  mysql:
    image: mysql:8.0.33
    ports: [ '8033:3306' ]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: test
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      start_period: 1s
      interval: 1s
      timeout: 2s
      retries: 60

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - $PWD:/app
    depends_on:
      - mysql
    environment:
      MYSQL_DSN: root:@tcp(mysql)/test